import js from '@eslint/js';
import pluginVue from 'eslint-plugin-vue';

export default [
  js.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  {
    files: ['**/*.{js,mjs,cjs,vue}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        Element: 'readonly',
        Document: 'readonly',
        Node: 'readonly',
        XMLHttpRequest: 'readonly',
        WebSocket: 'readonly',
        EventSource: 'readonly',
        Image: 'readonly',
        Audio: 'readonly',
        Video: 'readonly',
        MediaStream: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        AbortController: 'readonly',
        ReadableStream: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        // Node globals (per Vite)
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        // Alpine.js global (se lo usi)
        Alpine: 'readonly',
        // Three.js (per il tuo file Vue)
        THREE: 'readonly',
        LivekitClient: 'readonly',
      },
    },
    rules: {
      // Regole Vue personalizzate (puoi modificarle)
      'vue/multi-word-component-names': 'warn',
      'vue/no-unused-vars': 'warn',
      'vue/no-unused-components': 'warn',
      'vue/require-default-prop': 'warn',
      'vue/require-prop-types': 'warn',
      'vue/no-dupe-keys': 'error',
      'vue/no-mutating-props': 'error',
      'vue/order-in-components': 'warn',
      // Regole di formattazione Vue (disabilitate o warning)
      'vue/max-attributes-per-line': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/first-attribute-linebreak': 'off',
      'vue/attributes-order': 'off',
      // Regole JavaScript
      'no-unused-vars': 'warn',
      'no-console': 'off',
      'no-empty': 'warn',
      'no-undef': 'error',
      'no-useless-escape': 'warn',
      'no-cond-assign': 'warn',
    },
  },
  {
    // Ignora file specifici
    ignores: [
      'vendor/**',
      'node_modules/**',
      'public/**',
      'public_html/**',
      'storage/**',
      'bootstrap/cache/**',
      'laradock/**',
      'build/**',
      '.vite/**',
      'packages/**',
      '*.config.js',
      'postcss.config.js',
      'tailwind.config.js',
      'vite.config.js',
    ],
  },
];

